version: '3'
services:
  node1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stormdb1
    ports:
      - "5433:5432"

  node2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stormdb2
    ports:
      - "5434:5432"

  node3:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stormdb3
    ports:
      - "5435:5432"

  node2-replica:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stormdb2
    ports:
      - "5436:5432"